dist: xenial
os: linux
language: minimal
git:
  depth: 2
cache:
  ccache: true
  directories:
    - depends/built
    - depends/sdk-sources
    - $HOME/.ccache
services:
  - docker
stages:
  - test
env:
  global:
    - MAKEJOBS=-j3
    - RUN_UNIT_TESTS=true
    - RUN_FUNCTIONAL_TESTS=true
    - RUN_FUZZ_TESTS=false
    - DOCKER_NAME_TAG=ubuntu:18.04
    - BOOST_TEST_RANDOM=1$TRAVIS_BUILD_ID
    - CCACHE_SIZE=100M
    - CCACHE_TEMPDIR=/tmp/.ccache-temp
    - CCACHE_COMPRESS=1
    - CCACHE_DIR=$HOME/.ccache
    - DOCKER_PACKAGES="software-properties-common build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git ca-certificates ccache cmake"
before_install:
  - set -o errexit; source .travis/test_03_before_install.sh
install:
  - set -o errexit; source .travis/test_04_install.sh
before_script:
  - set -o errexit; source .travis/test_05_before_script.sh
script:
  - if [ $SECONDS -gt 1200 ]; then set +o errexit; echo "Travis early exit to cache current state"; false; else set -o errexit; source .travis/test_06_script_a.sh; fi
  - if [ $SECONDS -gt 1800 ]; then set +o errexit; echo "Travis early exit to cache current state"; false; else set -o errexit; source .travis/test_06_script_b.sh; fi
after_script:
  - echo $TRAVIS_COMMIT_RANGE
  - echo $TRAVIS_COMMIT_LOG
jobs:
  include:

    - stage: test
      name: 'x86_64 Linux  [GOAL: functinal test]  [xenial]  [no depends, only system libs, sanitizers: thread (TSan), no wallet]'
      env: >-
        HOST=""
        RUN_FUZZ_TESTS=false
        PACKAGES="clang llvm qtbase5-dev qttools5-dev-tools libssl-dev libevent-dev bsdmainutils libboost-all-dev libprotobuf-dev protobuf-compiler qrencode libgmp-dev"
        NO_DEPENDS=1
        GOAL="install"
        QTUM_CONFIG="--enable-bitcore-rpc CC=clang CXX=clang++"

    - stage: test
      name: 'macOS 10.10  [GOAL: build]'
      env: >-
        HOST="x86_64-apple-darwin14"
        RUN_UNIT_TESTS=false
        RUN_FUNCTIONAL_TESTS=false
        PACKAGES="clang llvm qtbase5-dev qttools5-dev-tools libssl-dev libevent-dev bsdmainutils libboost-all-dev libprotobuf-dev protobuf-compiler qrencode libgmp-dev"
        NO_DEPENDS=1
        GOAL="install"
        QTUM_CONFIG="CC=clang CXX=clang++"
